# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Fuse-DBI
version:      0.08
version_from: DBI.pm
installdirs:  site
requires:
    Carp:                          0
    DBI:                           0
    File::Find:                    0
    Fuse:                          0
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
